### ISSUE TITLE
Image is not deleted from printer

### ISSUE THREAD

**Issue by stephanlascar** [kylemacfarlane/zplgrf#3]
Hi,

We have notice graphics are not deleted from printer. The IDR command seems to not working...

https://github.com/kylemacfarlane/zplgrf/blob/aacad3e69c7abe04dbfe9ce3c5cf6ac2a1ab67b3/src/zplgrf/__init__.py#L346

I have change the ZPL command in order to include the IDR command in the "transaction". The IDR command is now just before the XZ command. It seems to work.

Is there any good reason this IDR command is outside the transaction ?

**Comment by kylemacfarlane** [comment]
Yes, it is how the official driver does it: https://github.com/apple/cups/blob/master/filter/rastertolabel.c#L615-L616

Your problem is mentioned in the comment above the line you linked:

https://github.com/kylemacfarlane/zplgrf/blob/aacad3e69c7abe04dbfe9ce3c5cf6ac2a1ab67b3/src/zplgrf/__init__.py#L327-L330

**Comment by kylemacfarlane** [comment]
This bug on the CUPS repo indicates it's a bad idea to put ^IDR before ^XZ: https://github.com/apple/cups/issues/4898

I noticed that I left off the ^FS at the end so it could be that your printer isn't processing the delete command until the next command (which in this case wouldn't be until the next label is printed).

**Comment by kylemacfarlane** [comment]
I managed to recreate the problem on a Citizen printer.

^FS makes no difference.

^IDR after ^XZ doesn't work on ZPL1.

^IDR before ^XZ causes a blank label on ZPL2.

The solution seems to be ^IDR inside its own ^XA^IDR^XZ block but maybe that breaks on other printers.

I asked on the CUPS issue and see what they'll say. Since the purpose of this package was to debug CUPS filters I don't want to deviate the ZPL and GS options too far from how CUPS itself works. Currently I think the only deviations are to do with detecting/overriding orientation.

**Comment by stephanlascar** [comment]
Thank you to open it again.

Here, we use old ZPL1 printer...

**Comment by kylemacfarlane** [comment]
CUPS has changed so can you confirm changing the last line to `'^XA^IDR:%s.GRF^FS^XZ'` works on your printer?

**Comment by stephanlascar** [comment]
Yes, we test it multiple time today. The image is no more in the printer. In work (at lease, for us...)

**Comment by kylemacfarlane** [comment]
I've updated the package to 1.5 and put it on PyPI.

**Comment by stephanlascar** [comment]
Thank you !!!!
