### ISSUE TITLE
Zebra ZP505 doesn't print with the ~DGR generated from this script

### ISSUE THREAD

**Issue by optikalefx** [kylemacfarlane/zplgrf#7]
The exact same ZPL on the Zebra ZP450ctp works fine. But on my ZP505 it's blank and changes slightly how the feed of the paper works.

I've confirmed that ~DGR works on the 505, but just not with the converted ZPL from a PDF.  We did try compression=2 already, and had the same result.

Is there anyway perhaps, to have this utility us the ^GF command instead of the ~DGF command? I wonder if that would solve this.

I'm going to keep trying different things and report back for more information.

**Comment by kylemacfarlane** [comment]
This is a package for debugging the GRFs output by CUPS. CUPS doesn't use ^GR so there's no need to support it.

Your problem is mentioned in the source:

https://github.com/kylemacfarlane/zplgrf/blob/403ed11d2c798607602d80cb9d03601ed0b7e805/src/zplgrf/__init__.py#L327-L330

The printing code only exists to check that the rasters can be understood by the printer. I won't support any other print commands  but if there's a problem with the actual raster I'll look into it.

The ZPL commands I used are copied from the official Apple/Zebra filters so they should work for every printer. If you can print fine using either the Apple or Zebra rastertolabel on Linux/OSX then attach a copy of the original PDF and the ZPL output from CUPS.

If you're using a proprietary driver on Windows then most likely there's custom FedEx firmware on the printer that purposefully breaks things to prevent easy reselling of free printers. You can intercept on Windows by changing the COM port of the printer to "FILE" and it'll then prompt you to save to a file when you print. If it's due to closed source firmware then I won't support it but maybe they're doing something easily bypassed like hiding the origin off page.

**Comment by optikalefx** [comment]
Thanks for a quick response!

These are zebra printers from Fedex/UPS so maybe there's something there blocking. But for some more detail. The sample code on page 159 of https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf works just fine.

I have these printers hooked up using CUPS on raspberry pi. And I print using `lp -d <name> -o raw <file.zpl>` So there isn't really a driver at play. In CUPS its just the raw setting.

I've attached a PDF and ZPL converted with this tool which prints blank on the 505 but fine on the 450.

[test.pdf](https://github.com/kylemacfarlane/zplgrf/files/3781162/test.pdf)
https://share.getcloudapp.com/X6u2byN7

Thanks!

**Comment by optikalefx** [comment]
Also for reference for both of us, here's the exact make/model of the printer.

![image](https://user-images.githubusercontent.com/926885/67728447-a5604700-f9c3-11e9-822e-b15f4894fa9d.png)

**Comment by kylemacfarlane** [comment]
But what happens when you do a non-raw print through CUPS, i.e. `lp -d <printer> test.pdf`? There's no point investigating anything until it's confirmed that the proper Apple/Zebra "drivers" work on Linux.

If the Apple/Zebra filters work then I need a copy of the ZPL it generates. If it doesn't work then the problem is the printer and the next step would be to intercept a print from the official FedEx drivers on Windows to see what they changed.

**Comment by kylemacfarlane** [comment]
I found my old notes of how I recreated the CUPS flow on my Raspberry Pi which is what lead to this project.

pdftoraster (PDF => PWG):

```
cat input.pdf | /usr/bin/gs -dQUIET -dPARANOIDSAFER -dNOPAUSE -dBATCH -dNOINTERPOLATE -sDEVICE=cups -sstdout=%stderr -sOutputFile=%stdout -dAdvanceDistance=1000 -r203x203 -dDEVICEWIDTHPOINTS=288 -dDEVICEHEIGHTPOINTS=432 -dcupsBitsPerColor=1 -dcupsColorOrder=0 -dcupsColorSpace=3 -dcupsRowStep=200 -scupsPageSizeName=w288h432 -I/usr/share/cups/fonts -c "<</.HWMargins[0.000000 0.000000 0.000000 0.000000] /Margins[0 0]>>setpagedevice" -f -_ > intermediate.pwg
```

rastertolabel (PWG => GRF wrapped in ZPL):

```
export PPD="/etc/cups/ppd/myprinter.ppd"
cat intermediate.pwg | /usr/lib/cups/filter/rastertolabel 1087 user "input.pdf" 1 "PageSize=w288h432 Resolution=203dpi job-uuid=urn:uuid:7d45d3fb-2b57-3b9e-794e-4cc07b00f0c9 job-originating-host-name=localhost time-at-creation=1462489313 time-at-processing=1462489313" > output.zpl
```
So if a non-raw print through CUPS works run these commands to recreate it manually and get the ZPL.

The outputs from CUPS and this project won't be exactly the same as I tweaked some things like scaling and orientation to auto-guess since it has to work without the printer information in the PPD.

BTW you're going to have problems with your packing slips being in jumbled order once they run over multiple pages so you'll have to manually reverse the order of the GRFs. Don't try to use ^PO to flip the orientation as that moves the origin as well which causes more trouble than it's worth.

**Comment by optikalefx** [comment]
Ok, I've got some new info.

1) I tried one of your sample ZPLs and it's also blank
2) I installed the same printer on the pi with the EPL2 driver, and printed with `lp`. It printed using EPL2, but was blank when selecting the ZPL driver. (This was the same thing on my mac btw)
3) I tried printing the ZPL with the ZPL driver, still blank.

I'll work on the raster method next to see if that works. I don't need packing slips, so that's not a concern.

**Comment by optikalefx** [comment]
So you've got `-sDEVICE=cups` did you have to setup anything special to get a ghostscript device as cups? It's not listed in my `gs -h` and says `Unknown device: cups`

**Comment by optikalefx** [comment]
Ok, I got your library to work on these printers. I had to change `^FO0,0` to `^FO6,6` or greater. The docs for ~DG have a sample at 20x20 which is what I originally tried. 5,5 does not work but 6,6 does. Perhaps that or the entire ZPL could be configurable in this library?

Thanks for all your help!

**Comment by kylemacfarlane** [comment]
As the GRFs are confirmed to work on the printer there is no bug. The example ZPL is not expected to work on all printers and will never be more configurable.

**Comment by kylemacfarlane** [comment]
BTW I don't think ^FO6,6 should really make that much difference? That's 6 dots which at 203dpi / 8 dots per mm is less than a mm adjustment? How could that be the difference between the whole label appearing or not? ^FO0,0 should still work but be slightly cut off.

Maybe if the printer is calibrated with margins in the LCD it'll refuse to print if the origin is beyond the thermal head?

I installed the ZP505 (actually installs as ZP500) driver on Windows and printed to a file. This was the output:

```
^CT~~CD,~CC^~CT~
^XA~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR5,5~SD26^JUS^LRN^CI0^XZ
^XA
^MMT
^PW812
^LL1218
^LS0
^FO0,0^GFA,129792,129792,00104,:Z64:
[data]
^PQ1,0,1,Y^XZ
```
They use field origin 0,0 (also notice label home 0,0 as well) but obviously I don't have a printer to actually test it on. But also there's like 20 preceding commands resetting the printer state. It would make more sense that one of these commands is the "real" solution.

**Comment by optikalefx** [comment]
I will give this a shot and see if these commands make it work with a field origin of zero

**Comment by optikalefx** [comment]
In reference to "will never be more configurable." Why is that? Wouldn't you want the ability to use this library in more than just the base case?

**Comment by kylemacfarlane** [comment]
> In reference to "will never be more configurable." Why is that? Wouldn't you want the ability to use this library in more than just the base case?

Because it's a can of worms and 99% of the problems are due to people not having their printer set to factory defaults. Right now you just want ^FO but look at how many commands the ZP505 uses to reset itself and imagine what a mess it'll be in a few years to support hundreds of printers from different manufacturers and every random state people have left their printer in.

If people need to wrap up the GRFs in their own ZPL for their very specific printer state then they can subclass it or use to_zpl_line() instead of to_zpl(). In my current refactor I've removed some printing options and moved what's left to separate classes to make it more obvious that the printing code isn't a core part of the package and you're supposed to "plugin" your own printer class. I still need to properly test Brother and IPP/PWG support before I release anything.

The options currently available are slightly more than what Apple and Zebra offer on Linux and OSX. If they've never seen a need to add more then I don't see why I should take on that burden either.

**Comment by optikalefx** [comment]
Thanks, and sorry for all the back and forth. I'm not a python guy, so I didn't understand that I could subclass this and extend the method. I was under the impression that there was just no way to customize this without forking your repo.

**Comment by optikalefx** [comment]
Small update, even with the settings you gave me, it is still blank until I move the FO to at least 6,6. Quite interesting.

**Comment by kylemacfarlane** [comment]
I'm still interested in trying to figure out why it doesn't work as it's not far from how this project started which was "why are barcodes high quality on Windows and low quality on Linux/OSX?".

Here's the raw prints from Windows to see if sending them to the printer works.

[zp500-original.txt](https://github.com/kylemacfarlane/zplgrf/files/3790381/zp500-original.txt)
[zp500-cleaned.txt](https://github.com/kylemacfarlane/zplgrf/files/3790382/zp500-cleaned.txt)

zp500-original.txt for some reason starts with a CTRL+P character and I don't know if that's on purpose or some crap Windows added. zp500-cleaned.txt I changed it to what I assume it should look like in ZPL.

Zplgrf can extract the rasters from these (once you edit them to use ~DGR) but when I recompress them the compressed data is slightly different. The difference is caused by zlib so it's not something I can fix (I did try different zlib compression levels to see if one would match Windows) but I don't think it matters anyway. There's no way to change the compression type on Windows so you can't get a comparison for the ASCII run length compression.

If this ZPL doesn't work then you should get the printer setup on Windows yourself and if that still doesn't work you should be able to get support from Zebra/Fedex. In my experience no printer manufacturer will help you on Linux or OSX.

Some other things to try:

- Does the ~DGR example in the docs work at 0,0? If it does maybe the problem is something to do with label width/height.
- Check if ^FO6,0 or ^FO0,6 works to figure out if it's a horizontal or vertical problem.
- Try changing the label home/origin to ^LH6,6 but keep ^FO0,0
- Try keeping everything at 0,0 but set left shift to ^LS6 and/or label top to ^LT6: https://www.zebra.com/us/en/support-downloads/knowledge-articles/adjusting-left-position-and-top-position-on-zebra-barcode-printers.html

The latter is what I think the adjustments on the LCD screens do. If they work you can then persist them with ^JUS and that'd fix printing from CUPS too.

**Comment by kylemacfarlane** [comment]
What happens if you draw regular text at 0,0? I still think the most logical explanation is that somehow 0,0 has been moved off the label which makes the ZP505 ignore the whole raster.

However according to this page text should be drawn even if it's off the label: https://www.zebra.com/us/en/support-downloads/knowledge-articles/adjusting-left-position-and-top-position-on-zebra-barcode-printers.html

So in theory if the origin is -6 horizontally off the page then text drawn at 0,y 1,y 2,y etc should all appear in the same horizontal position. If it's -6 vertically it should bleed off the label.

**Comment by optikalefx** [comment]
I'm going to test these out soon and let you know. Meanwhile, did you find a way to do this conversion in something other than Ghostscript? Their license doesn't allow for commercial software.

**Comment by kylemacfarlane** [comment]
Maybe PDFium (Google's PDF reader for Chrome and Googlebot) can do it but I don't think it has a CLI so you'd have to find some bindings to wrap it up. You'd also have to figure out the scaling options so it doesn't wreck barcode quality like Ghostscript does without the center of pixel option.

For the higher end Zebra printers you can buy a license to add direct PDF printing (it's probably a Ghostscript license running on the printers).
